export enum RouteName {
  ROOT = "/",
  MAIN = "/main",
  ADMIN_LOGIN = "/admin-login",
  CONTACT = "/contact",
  CART = "/cart",
  CHECKOUT = "/checkout",
  PRODUCTS = "/products",
  ADD_PRODUCTS = "/add-products",
  ORDERS = "/orders",
  ADDNEWORDER= "/add-new-order",
  ABOUT = "/about",
  DASHBOARD = "/dashboard",
  PRODUCT_PAGE = "/product-details",
}
